#!/bin/sh
set -e
for f in /usr/share/nginx/html/*.js; do
  envsubst '${BACKEND_LINK} ${BACKEND_USER_LINK} ${BACKEND_CHAT_LINK} ${BACKEND_UBS_LINK} ${FRONTEND_LINK} ${SOCKET} ${CHAT_SOCKET} ${API_KEYS} ${API_MAP_KEY} ${FIREBASE_API_KEY} ${FIREBASE_AUTH_DOMAIN} ${FIREBASE_DATABASE_URL} ${FIREBASE_PROJECT_ID} ${FIREBASE_STORAGE_BUCKET} ${FIREBASE_MESSAGING_SENDER_ID} ${FIREBASE_APP_ID} ${FIREBASE_MEASUREMENT_ID} ${BACKEND_UBS_ADMIN_LINK} ${GOOGLE_CLIENT_ID} ${AGM_CORE_MODULE_API_KEY}' < "$f" > "$f.tmp" && mv "$f.tmp" "$f"
done
exec nginx -g 'daemon off;'
