upstream core_backend {
    server core:8080 max_fails=3 fail_timeout=10s;
}

upstream user_backend {
    server user:8060 max_fails=3 fail_timeout=10s;
}

server {
    listen 8080;
    client_max_body_size 100m;   # backcore: spring.servlet.multipart.max-request-size=100MB

    location /socket {
        proxy_pass http://core_backend;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
        proxy_read_timeout 3600s;
    }

    location / {
        proxy_pass http://core_backend;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}

server {
    listen 8060;
    client_max_body_size 10m;    # backuser: spring.servlet.multipart.max-request-size=10MB

    location / {
        proxy_pass http://user_backend;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
